export const overridesLight = {
    "paneProperties.topMargin": 10,
    "paneProperties.bottomMargin": 25,
    "paneProperties.legendProperties.showStudyArguments": false,
    "paneProperties.legendProperties.showStudyTitles": true,
    "paneProperties.legendProperties.showStudyValues": true,
    "paneProperties.legendProperties.showSeriesTitle": false,
    "paneProperties.legendProperties.showSeriesOHLC": true,
    "paneProperties.background": "#fff",    // 整体背景颜色
    "paneProperties.vertGridProperties.color": "#eee",  // 格子竖线的颜色
    "paneProperties.horzGridProperties.color": "#eee",  // 格子横线的颜色
    "paneProperties.crossHairProperties.color": "#222", // 十字线的颜色
    "scalesProperties.showLeftScale": false,    // 是否显示左侧的比例
    "scalesProperties.showRightScale": true,    // 是否显示右侧的比例
    "scalesProperties.scaleSeriesOnly": false,  //
    "scalesProperties.showSymbolLabels": true,  //
    "scalesProperties.lineColor": "#222",   // 横纵坐标线颜色   
    "scalesProperties.textColor": "#222",   // 横纵坐标文字
    "dataWindowProperties.visible": false,  // 
    "dataWindowProperties.font": "Open Sans, Verdana",
    "dataWindowProperties.fontSize": 8,
    "symbolWatermarkProperties.color": "#666",  // 图表中间显示的symbol水印颜色
    "symbolWatermarkProperties.transparency": 85,   // 图表中间显示的symbol水印透明度
    "mainSeriesProperties.showLastValue": true,
    "mainSeriesProperties.visible": true,   // 显示主数据，就是合约的趋势图
    "mainSeriesProperties.showPriceLine": true, // 显示当前价格的一整条线
    "mainSeriesProperties.priceAxisProperties.autoScale": true,
    "mainSeriesProperties.priceAxisProperties.autoScaleDisabled": false,
    "mainSeriesProperties.priceAxisProperties.percentage": false,   // 纵坐标价格是否显示为百分比
    "mainSeriesProperties.priceAxisProperties.percentageDisabled": false,
    "mainSeriesProperties.priceAxisProperties.log": false,
    "mainSeriesProperties.priceAxisProperties.logDisabled": false,
    "mainSeriesProperties.candleStyle.upColor": "#52b370",  // 上涨的颜色
    "mainSeriesProperties.candleStyle.downColor": "#e8704f",    // 下跌的颜色
    "mainSeriesProperties.candleStyle.drawWick": true,
    "mainSeriesProperties.candleStyle.drawBorder": true,
    "mainSeriesProperties.candleStyle.borderColor": "#378658",  // 边框的颜色
    "mainSeriesProperties.candleStyle.borderUpColor": "#205536",
    "mainSeriesProperties.candleStyle.borderDownColor": "#5C1A10",
    "mainSeriesProperties.candleStyle.wickColor": "#737375",    // 烛芯的颜色
    "mainSeriesProperties.candleStyle.wickUpColor": "#388d53",
    "mainSeriesProperties.candleStyle.wickDownColor": "#d56161",
    "mainSeriesProperties.candleStyle.barColorsOnPrevClose": false,
    "mainSeriesProperties.hollowCandleStyle.upColor": "#52b370",
    "mainSeriesProperties.hollowCandleStyle.downColor": "#e8704f",
    "mainSeriesProperties.hollowCandleStyle.drawWick": true,
    "mainSeriesProperties.hollowCandleStyle.drawBorder": true,
    "mainSeriesProperties.hollowCandleStyle.borderColor": "#378658",
    "mainSeriesProperties.hollowCandleStyle.borderUpColor": "#205536",
    "mainSeriesProperties.hollowCandleStyle.borderDownColor": "#5C1A10",
    "mainSeriesProperties.hollowCandleStyle.wickColor": "#737375",
    "mainSeriesProperties.hollowCandleStyle.wickUpColor": "#388d53",
    "mainSeriesProperties.hollowCandleStyle.wickDownColor": "#d56161",
    "mainSeriesProperties.haStyle.upColor": "#52b370",
    "mainSeriesProperties.haStyle.downColor": "#e8704f",
    "mainSeriesProperties.haStyle.drawWick": true,
    "mainSeriesProperties.haStyle.drawBorder": true,
    "mainSeriesProperties.haStyle.borderColor": "#378658",
    "mainSeriesProperties.haStyle.borderUpColor": "#205536",
    "mainSeriesProperties.haStyle.borderDownColor": "#5C1A10",
    "mainSeriesProperties.haStyle.wickColor": "#737375",
    "mainSeriesProperties.haStyle.wickUpColor": "#388d53",
    "mainSeriesProperties.haStyle.wickDownColor": "#d56161",
    "mainSeriesProperties.haStyle.barColorsOnPrevClose": false,
    "mainSeriesProperties.barStyle.upColor": "#52b370",
    "mainSeriesProperties.barStyle.downColor": "#e8704f",
    "mainSeriesProperties.barStyle.barColorsOnPrevClose": false,
    "mainSeriesProperties.barStyle.dontDrawOpen": false,
    "mainSeriesProperties.lineStyle.color": "#c0d2df",
    "mainSeriesProperties.lineStyle.linewidth": 1,
    "mainSeriesProperties.lineStyle.priceSource": "close",
    "mainSeriesProperties.areaStyle.color1": "#52b370",
    "mainSeriesProperties.areaStyle.color2": "#e8704f",
    "mainSeriesProperties.areaStyle.linecolor": "#c0d2df",
    "mainSeriesProperties.areaStyle.linewidth": 1,
    "mainSeriesProperties.areaStyle.priceSource": "close",
    "mainSeriesProperties.areaStyle.transparency": 50,
    "mainSeriesProperties.renkoStyle.upColor": "#52b370",
    "mainSeriesProperties.renkoStyle.downColor": "#e8704f",
    "mainSeriesProperties.pbStyle.upColor": "#52b370",
    "mainSeriesProperties.pbStyle.downColor": "#e8704f",
    "mainSeriesProperties.kagiStyle.upColor": "#52b370",
    "mainSeriesProperties.kagiStyle.downColor": "#e8704f",
    "mainSeriesProperties.pnfStyle.upColor": "#52b370",
    "mainSeriesProperties.pnfStyle.downColor": "#e8704f"
};

export const overridesDark = {
    "paneProperties.topMargin": 10,
    "paneProperties.bottomMargin": 25,
    "paneProperties.legendProperties.showStudyArguments": false,
    "paneProperties.legendProperties.showStudyTitles": true,
    "paneProperties.legendProperties.showStudyValues": true,
    "paneProperties.legendProperties.showSeriesTitle": false,
    "paneProperties.legendProperties.showSeriesOHLC": true,
    "scalesProperties.showLeftScale": false,
    "scalesProperties.showRightScale": true,
    "scalesProperties.scaleSeriesOnly": false,
    "scalesProperties.showSymbolLabels": true,
    "mainSeriesProperties.priceAxisProperties.autoScale": true,
    "mainSeriesProperties.priceAxisProperties.autoScaleDisabled": false,
    "mainSeriesProperties.priceAxisProperties.percentage": false,
    "mainSeriesProperties.priceAxisProperties.percentageDisabled": false,
    "mainSeriesProperties.priceAxisProperties.log": false,
    "mainSeriesProperties.priceAxisProperties.logDisabled": false,
    "mainSeriesProperties.showLastValue": true,
    "mainSeriesProperties.visible": true,
    "mainSeriesProperties.showPriceLine": true,
    "dataWindowProperties.visible": false,
    "dataWindowProperties.font": "Open Sans, Verdana",
    "dataWindowProperties.fontSize": 8,
    "paneProperties.background": "#23303b",
    "paneProperties.vertGridProperties.color": "#344959",
    "paneProperties.horzGridProperties.color": "#344959",
    "paneProperties.crossHairProperties.color": "#eee",
    "scalesProperties.lineColor": "#eee",
    "scalesProperties.textColor": "#eee",
    "symbolWatermarkProperties.color": "#f8f8f8",
    "symbolWatermarkProperties.transparency": 100,
    "mainSeriesProperties.candleStyle.upColor": "#24b36b",
    "mainSeriesProperties.candleStyle.downColor": "#e34e4d",
    "mainSeriesProperties.candleStyle.drawWick": true,
    "mainSeriesProperties.candleStyle.drawBorder": false,
    "mainSeriesProperties.candleStyle.borderColor": "#378658",
    "mainSeriesProperties.candleStyle.borderUpColor": "#24b36b",
    "mainSeriesProperties.candleStyle.borderDownColor": "#e34e4d",
    "mainSeriesProperties.candleStyle.wickColor": "#737375",
    "mainSeriesProperties.candleStyle.wickUpColor": "#27c073",
    "mainSeriesProperties.candleStyle.wickDownColor": "#f45453",
    "mainSeriesProperties.candleStyle.barColorsOnPrevClose": false,
    "mainSeriesProperties.hollowCandleStyle.upColor": "#24b36b",
    "mainSeriesProperties.hollowCandleStyle.downColor": "#e34e4d",
    "mainSeriesProperties.hollowCandleStyle.drawWick": true,
    "mainSeriesProperties.hollowCandleStyle.drawBorder": true,
    "mainSeriesProperties.hollowCandleStyle.borderColor": "#378658",
    "mainSeriesProperties.hollowCandleStyle.borderUpColor": "#24b36b",
    "mainSeriesProperties.hollowCandleStyle.borderDownColor": "#e34e4d",
    "mainSeriesProperties.hollowCandleStyle.wickColor": "#737375",
    "mainSeriesProperties.hollowCandleStyle.wickUpColor": "#27c073",
    "mainSeriesProperties.hollowCandleStyle.wickDownColor": "#f45453",
    "mainSeriesProperties.haStyle.upColor": "#24b36b",
    "mainSeriesProperties.haStyle.downColor": "#e34e4d",
    "mainSeriesProperties.haStyle.drawWick": true,
    "mainSeriesProperties.haStyle.drawBorder": true,
    "mainSeriesProperties.haStyle.borderColor": "#378658",
    "mainSeriesProperties.haStyle.borderUpColor": "#24b36b",
    "mainSeriesProperties.haStyle.borderDownColor": "#e34e4d",
    "mainSeriesProperties.haStyle.wickColor": "#737375",
    "mainSeriesProperties.haStyle.wickUpColor": "#27c073",
    "mainSeriesProperties.haStyle.wickDownColor": "#f45453",
    "mainSeriesProperties.haStyle.barColorsOnPrevClose": false,
    "mainSeriesProperties.barStyle.upColor": "#24b36b",
    "mainSeriesProperties.barStyle.downColor": "#e34e4d",
    "mainSeriesProperties.barStyle.barColorsOnPrevClose": false,
    "mainSeriesProperties.barStyle.dontDrawOpen": false,
    "mainSeriesProperties.lineStyle.color": "#618fb0",
    "mainSeriesProperties.lineStyle.linewidth": 1,
    "mainSeriesProperties.lineStyle.priceSource": "close",
    "mainSeriesProperties.areaStyle.color1": "#24b36b",
    "mainSeriesProperties.areaStyle.color2": "#e34e4d",
    "mainSeriesProperties.areaStyle.linecolor": "#618fb0",
    "mainSeriesProperties.areaStyle.linewidth": 1,
    "mainSeriesProperties.areaStyle.priceSource": "close",
    "mainSeriesProperties.areaStyle.transparency": 50,
    "mainSeriesProperties.renkoStyle.upColor": "#24b36b",
    "mainSeriesProperties.renkoStyle.downColor": "#e34e4d",
    "mainSeriesProperties.pbStyle.upColor": "#24b36b",
    "mainSeriesProperties.pbStyle.downColor": "#e34e4d",
    "mainSeriesProperties.kagiStyle.upColor": "#24b36b",
    "mainSeriesProperties.kagiStyle.downColor": "#e34e4d",
    "mainSeriesProperties.pnfStyle.upColor": "#24b36b",
    "mainSeriesProperties.pnfStyle.downColor": "#e34e4d"
};

export const lightColor = {
    orderBuy: 'rgb(63,160,94)',
    orderSell: 'rgb(226,83,46)',
    positionBuy: 'rgb(63,160,94)',
    positionSell: 'rgb(226,83,46)',
    toolbarBackground: 'transparent',
}

export const darkColor = {
    orderBuy: '#24b36b',
    orderSell: '#e34e4d',
    positionBuy: '#24b36b',
    positionSell: '#e34e4d',
    toolbarBackground: '#23303B',
}